import SwiftUI

struct DetailAsanaModel {
    
    var image : String 
    var description : String 
    var steps : [String]
    var benefits : [String]
    var precautions : [String]
    var videoName : String
}


//sources of this description, steps, benefits and precautions is wikipedia and various books 

//videos are made by me 
var detailsAsana : [String : DetailAsanaModel] = [
    "Bhujangasana" : DetailAsanaModel(image: "bhujangasana1",
                                      description: "Bhujangasana (Cobra Stretch) comes from the word bhujanga meaning cobra or snake and asana meaning pose. Bhujangasana is also known as Cobra Stretch. This pose is included in Suryanamaskar (Sun Salutations Pose) as well as Padma Sadhana. ",
                                      steps: ["1. Lie down on your stomach with your toes flat on the floor, soles facing upwards; rest your forehead on the ground.","2. Keep your legs close together, with your feet and heels lightly touching each other.","3. Place both hands in such a way that palms are touching ground under your shoulders, elbows should be parallel and close to your torso","4. Taking a deep breath in, slowly lift your head, chest and abdomen. Keep your navel on the floor.","5. Pull your torso back and off the floor with the support of your hands. Make sure that you are putting equal pressure on both the palms.","6. Keep breathing with awareness, as you curve your spine, vertebra by vertebra. If possible, straighten your arms by arching your back as much as possible; tilt your head back and look up ", "7. Maintain the pose while breathing evenly for 4-5 breaths. ", "8. Now, breathe out, and gently bring your abdomen, chest, and head back to the floor and relax."],
                                      benefits: ["Opens up the shoulders and neck to relieve pain", "Strengthens the entire back and shoulders","Improves flexibility of the upper and middle back","Expands the chest","Improves blood circulation","Reduces fatigue and stress","Useful for people with respiratory disorders such as asthma"],
                                      precautions: ["Avoid practicing Bhujangasana if you are pregnant.","Do not practice it if you have fractured ribs or wrists, or have recently undergone abdominal surgeries, such as for hernia.","Avoid doing Bhujangasana if you suffer from Carpal Tunnel Syndrome.","Do not practice this yoga pose during an asthmatic attack. ","Practice the Cobra Pose under a trained teacher for guidance if you have suffered from chronic diseases or spinal disorders in the past.","ideally, all yoga asanas should be done under the proper guidance of a trained teacher."],
                                      videoName: "BhujangasanaVideo"),
    
    "Vajrasana" : DetailAsanaModel(image: "vajrasana",
                                   description: "Vajrasana gets its name from the Sanskrit word vajra, which means thunderbolt or diamond. Vajrasana pose is a simple sitting yoga posture that has several possible benefits, such as reducing back pain, improving focus, and helping to manage symptoms of hypertension.",
                                   steps: ["1. Start by kneeling on the floor. Consider using a yoga mat for comfort.","2. Pull your knees and ankles together and point your feet in line with your legs. The bottoms of your feet should face upward with your big toes touching.", "3. Exhale as you sit back on your legs. Your buttocks will rest on your heels and your thighs will rest on your calves.", "4. Put your hands on your thighs and adjust your pelvis slightly backward and forward until you’re comfortable.", "5. Breathe in and out slowly as you position yourself to sit up straight by straightening your spine. Use your head to pull your body upward and press your tailbone toward the floor.","6. Straighten your head to gaze forward with your chin parallel to the floor. Position your hands palms down on your thighs with your arms relaxed."],
                                   benefits: ["improve attention","reduce anxiety","improve flexibility","decrease blood pressure and heart rate","help to manage Source symptoms of type 2 diabetes","It is important to remember that you should not replace any of your existing treatment options, like medication, with yoga unless you have spoken with a healthcare professional."],
                                   precautions: ["It is important to remember that you should not replace any of your existing treatment options, like medication, with yoga unless you have spoken with a healthcare professional.", "Avoid Vajrasana if you have a knee problem or have recently undergone knee surgery","Avoid Vajrasana if you have a spinal cord condition, especially with the lower vertebrae","Avoid Vajrasana if you have a intestinal ulcers, a hernia, or any other intestinal problems such as an ulcer or hernia"],
                                   videoName : "VajrasanaVideo"),
    
    "Vrikshasana" : DetailAsanaModel(image: "vrikshasana12",
                                     description: "The Sanskrit word”vriksha” means tree. Standing straight on the left leg, bend the right leg and place the right foot on the root of the left thigh.  Stand thus like a tree on the ground. This is called “vriksha-asana.” ",
                                     steps: ["1. Stand with the feet together and the arms by your sides (see the tad-asana). ","2. Bend the right leg at the knee, raise the right thigh and bring the sole of the right foot as high up  the inside of the left thigh as possible.","3. Balancing on the left foot, raise both arms over the head keeping the elbows unbent and joining  the palms together. Hold the posture while breathing gently through the nostrils for about 10  complete breaths.  ","4. Lower the arms and right leg and return to the tad-asana, standing position with feet together  and arms at the sides. Pause for a few moments and repeat on the opposite leg.  "],
                                     benefits: ["This pose leaves you in a state of rejuvenation. It stretches the legs, back and    arms, and invigorates you.","It brings balance and equilibrium to your mind.","It helps improve concentration.","This posture has been found to relieve some cases of sciatica.","It makes the legs strong, improves balance, and opens the hips.","Helps those who are suffering from sciatica."],
                                     precautions: ["Avoid doing this posture if you are suffering from migraine","Avoid doing this posture if you are suffering from insomnia","void doing this posture if you are suffering from low or high blood pressure"],
                                     videoName: "VrikshasanaVideo"),
    
    "Sarvangasana" : DetailAsanaModel(image: "sarvangasana1",
                                      description: "Sarvangasana or shoulder stand is a yoga pose wherein the whole body is balanced on the shoulders. ‘Sarv’ means all, ‘anga’ means part of a body, and ‘asana’ is posture. As the name indicates, Sarvangasana influences the functioning of all parts of your body. This asana is highly beneficial in maintaining the mental and physical health and is also referred as ‘Queen of asanas’.",
                                      steps: ["1. Lie on your back with hands by your side","2. With one movement, lift your legs, buttocks and back so that you come up high on your shoulders. Support your back with the hands.","3. Move your elbows closer towards each other, and move your hands along your back, creeping up towards the shoulder blades. Keep straightening the legs and spine by pressing the elbows down to the floor and hands into the back. Your weight should be supported on your shoulders and upper arms and not on your head and neck.","4. Keep the legs firm. Lift your heels higher as though you are putting a footprint on the ceiling. Bring the big toes straight over the nose. Now point the toes up. Pay attention to your neck. Do not press the neck into the floor. Instead keep the neck strong with a feeling of tightening the neck muscles slightly. Press your sternum toward the chin. If you feel any strain in the neck, come out of the posture.","5. Keep breathing deeply and stay in the posture for 30-60 seconds.","6. To come out of the posture, lower the knees to forehead. Bring your hands to the floor, palms facing down. Without lifting the head slowly bring your spine down, vertebra by vertebra, completely to the floor.","7. Lower the legs to the floor. Relax for a minimum of 60 seconds.","8. Hold the sarvanga-asana anywhere from one to five minutes depending on comfort. Repeat the posture  two or three times."],
                                      benefits: ["Stimulates the thyroid and parathyroid glands and normalizes their functions","Strengthens the arms and shoulders and keeps the spine flexible","Nourishes the brain with more blood","Stretches the heart muscles by returning more venous blood to the heart","Brings relief from constipation, indigestion and varicose veins"],
                                      precautions: ["Consult your physician before doing the Sarvangasana if you have any of the following health conditions: pregnancy, menstruation, high blood pressure, heart problem, glaucoma, slip disc, spondylosis, neck pain and acute thyroid problem."],
                                      videoName: "SarvangasanaVideo"),
    
    "Padmasana" : DetailAsanaModel(image: "padmasana",
                                   description: "Padmasana or Lotus position is a cross-legged yoga posture which helps deepen meditation by calming the mind and alleviating various physical ailments. A regular practice of this posture aids in overall blossoming of the practitioner, just like a lotus; and hence the name Padmasana. In Chinese and Tibetan Buddhism, the Lotus pose is also known as Vajra position.",
                                   steps: ["1. Sit on the floor or on a mat with legs stretched out in front of you while keeping the spine erect.","2. Bend the right knee and place it on the left thigh. Make sure that the sole of the feet point upward and the heel is close to the abdomen.","3. Now, repeat the same step with the other leg.","4. With both the legs crossed and feet placed on opposite thighs, place your hands on the knees in mudra position.","5. Keep the head straight and spine erect.","6. Hold and continue with gentle long breaths in and out."],
                                   benefits: ["Improves digestion","Reduces muscular tension and brings blood pressure under control","Relaxes the mind","Helps pregnant ladies during childbirth","Reduces menstrual discomfort"],
                                   precautions: ["Consult your physician before doing the Padmasana if you have ankle or knee injury"],
                                   videoName: "PadmasanaVideo")
]
